# Site settings
title: Nightbug
email: team@nightb.ug
description: "It's not a feature, it's a bug!"
baseurl: ""
url: "http://yourdomain.com"
twitter_username: nightbugdev
github_username:  nightbug

# Build settings
markdown: kramdown
permalink: pretty
